# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYJPDzujI8h04-st2jiCzZt1WE4ctc9D
"""

import pandas as pd
teacher=pd.DataFrame({
    "FISH": ["Qadamova Z.E " ,  "   Abdullayeva M.R" , "Turdimatov M.M" ," Xonto'rayev S.I" , "Arabboyev A.A" ] ,
    "Fan nomi" : [ "Sun'iy intelekt asoslari " ,"Ma'lumot tuzilmasi va algorimlar" , " Kiberxavsizlik asoslari"  , "Ma'lumot tuzilmasi va algorimlar " , " Kiberxavsizlik asoslari" ] ,
"Mashg'ulot turi" : ["amaliy" ,"amaliy" ,"maruza" ,"maruza","amaliy"],
    "Dars o'tish mahorati": [ " yaxshi" ,"yaxshi" ,"yaxshi" ,"yaxshi","yaxshi"]
    })
print (teacher)

teacher.to_excel("teacher.xlsx")